# Site settings
title: JIUZHE
description: 记录学习和生活
author: JIUZHE

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

# Social media
github_username: forkicksinuk


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
lang: zh
timezone: Asia/Shanghai
url: "https://forkicks.fun"  # Updated to correct domain
baseurl: ""

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

highlighter: rouge