# 站点基本信息
title: JIUZHE BLOG
description: "live,laugh,love"
url: "https://forkicks.fun"
baseurl: ""  # 如果您的网站部署在子目录下，请填写子目录路径，否则留空

# 作者信息
author:
  name: 就这
  email: jiuzhey666@gmail.com

# 社交媒体设置
github_username: forkicksinuk

# 侧边栏设置
sidebar: true
sidebar-about-description: "live,laugh,love"

# 构建设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM  # 使用 GitHub 风格的 Markdown

# 分页设置
paginate: 10  # 每页显示的文章数
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-paginate

# 排除文件和文件夹
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md

# 其他设置
permalink: pretty
anchorjs: true
service-worker: true
chrome-tab-theme-color: "#000000"

# 站点地图和 SEO（可选）
# 如果需要站点地图和 SEO 支持，可以添加相应的插件和配置
