baseURL = 'https://forkicksinuk.github.io'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'forkicks 写字的地方'
theme = 'morandi'
ignoreFiles = ["/content/posts/_templates/"]

[params]
  description = "forkicks 的个人博客，记录关于技术、AI 和个人思考的点滴。"
  tagline = "一个写字的地方"
  author = "forkicks"
  keywords = ["技术博客", "AI", "编程", "个人思考", "开发工具", "静态网站"]
[params.giscus]
  enable = true
  repo = "forkicksinuk/forkicksinuk.github.io"
  repoId = "R_kgDOMxA5bQ"
  category = "General"
  categoryId = "DIC_kwDOMxA5bc4Cw8F9"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"
  loading = "lazy"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 5

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[module]
  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'images'
    target = 'static/images'
